ALTER TABLE DimCity MODIFY COLUMN CityKey INT NOT NULL AUTO_INCREMENT;
ALTER TABLE DimSensor MODIFY COLUMN SensorKey INT NOT NULL AUTO_INCREMENT;
ALTER TABLE DimLP MODIFY COLUMN LPKey INT NOT NULL AUTO_INCREMENT;
ALTER TABLE DimDetectionType MODIFY COLUMN DetectionTypeKey INT NOT NULL AUTO_INCREMENT;
ALTER TABLE DimCountry MODIFY COLUMN CountryKey INT NOT NULL AUTO_INCREMENT;
ALTER TABLE DimVehicleClass MODIFY COLUMN VehicleClassKey INT NOT NULL AUTO_INCREMENT;

