-- Povolí všechny funkce TimescaleDB (jako create_hypertable) v aktuální databázi
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- Vytvoření schématu, pokud neexistuje
CREATE SCHEMA IF NOT EXISTS mttgueries;

/*
=================================================
 SADA SKRIPTŮ PRO VYTVOŘENÍ DWH SCHÉMATU
 Cílová databáze: PostgreSQL s TimescaleDB
 Schéma: mttgueries
=================================================
*/

--===============================================
-- KROK 1: VYTVOŘENÍ DIMENZÍ (Doplněny explicitní UNIQUE indexy)
--===============================================

-- Dimenze Město (pro Bílinu, Děčín atd.)
DROP TABLE IF EXISTS mttgueries.DimCity CASCADE;
CREATE TABLE mttgueries.DimCity (
    CityKey INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CityName TEXT UNIQUE NOT NULL
);
INSERT INTO mttgueries.DimCity (CityKey, CityName) VALUES (-1, 'Unknown');
-- 💡 ZRYCHLENÍ: Explicitní index pro ON CONFLICT v ETL
CREATE UNIQUE INDEX idx_dimcity_name ON mttgueries.DimCity (CityName); 


-- Dimenze Senzor
DROP TABLE IF EXISTS mttgueries.DimSensor CASCADE;
CREATE TABLE mttgueries.DimSensor (
    SensorKey INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    SensorCode TEXT UNIQUE NOT NULL
);
INSERT INTO mttgueries.DimSensor (SensorKey, SensorCode) VALUES (-1, 'Unknown');
-- 💡 ZRYCHLENÍ: Explicitní index pro ON CONFLICT v ETL
CREATE UNIQUE INDEX idx_dimsensor_code ON mttgueries.DimSensor (SensorCode); 


-- Dimenze SPZ
DROP TABLE IF EXISTS mttgueries.DimLP CASCADE;
CREATE TABLE mttgueries.DimLP (
    LPKey INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    LicensePlate TEXT UNIQUE NOT NULL
);
INSERT INTO mttgueries.DimLP (LPKey, LicensePlate) VALUES (-1, 'Unknown');
-- 💡 ZRYCHLENÍ: Explicitní index pro ON CONFLICT v ETL
CREATE UNIQUE INDEX idx_dimlp_plate ON mttgueries.DimLP (LicensePlate); 


-- Dimenze Typ Detekce
DROP TABLE IF EXISTS mttgueries.DimDetectionType CASCADE;
CREATE TABLE mttgueries.DimDetectionType (
    DetectionTypeKey INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    DetectionType TEXT UNIQUE NOT NULL
);
INSERT INTO mttgueries.DimDetectionType (DetectionTypeKey, DetectionType) VALUES (-1, 'Unknown');
-- 💡 ZRYCHLENÍ: Explicitní index pro ON CONFLICT v ETL
CREATE UNIQUE INDEX idx_dimdetectiontype_type ON mttgueries.DimDetectionType (DetectionType); 


-- Dimenze Třída Vozidla
DROP TABLE IF EXISTS mttgueries.DimVehicleClass CASCADE;
CREATE TABLE mttgueries.DimVehicleClass (
    VehicleClassKey INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    VehicleClass TEXT UNIQUE NOT NULL
);
INSERT INTO mttgueries.DimVehicleClass (VehicleClassKey, VehicleClass) VALUES (-1, 'Unknown');
-- 💡 ZRYCHLENÍ: Explicitní index pro ON CONFLICT v ETL
CREATE UNIQUE INDEX idx_dimvehicleclass_class ON mttgueries.DimVehicleClass (VehicleClass); 


-- Dimenze Země
DROP TABLE IF EXISTS mttgueries.DimCountry CASCADE;
CREATE TABLE mttgueries.DimCountry (
    CountryKey INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CountryCode TEXT UNIQUE NOT NULL
);
INSERT INTO mttgueries.DimCountry (CountryKey, CountryCode) VALUES (-1, 'Unknown');
-- 💡 ZRYCHLENÍ: Explicitní index pro ON CONFLICT v ETL
CREATE UNIQUE INDEX idx_dimcountry_code ON mttgueries.DimCountry (CountryCode); 


--===============================================
-- KROK 2: VYTVOŘENÍ A NAPLNĚNÍ DIMENZE ČASU (Doplněn Index)
--===============================================

DROP TABLE IF EXISTS mttgueries.DimTime CASCADE;
CREATE TABLE mttgueries.DimTime (
    TimeKey INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    FullDate DATE NOT NULL,
    YearNum SMALLINT NOT NULL,
    MonthNum SMALLINT NOT NULL,
    DayNum SMALLINT NOT NULL,
    DayOfWeekNum SMALLINT NOT NULL,
    HourNum SMALLINT NOT NULL,
    MinuteNum SMALLINT NOT NULL,
    UNIQUE (FullDate, HourNum, MinuteNum)
);

-- 💡 ZRYCHLENÍ: Složený index pro zrychlení JOINu ve faktové tabulce
CREATE INDEX idx_dimtime_join ON mttgueries.DimTime (FullDate, HourNum, MinuteNum);


-- Vložení "Neznámého" záznamu
INSERT INTO mttgueries.DimTime (TimeKey, FullDate, YearNum, MonthNum, DayNum, DayOfWeekNum, HourNum, MinuteNum)
VALUES (-1, '1900-01-01', -1, -1, -1, -1, -1, -1);

-- Naplnění časové dimenze (např. na 2 roky dopředu)
INSERT INTO mttgueries.DimTime (FullDate, YearNum, MonthNum, DayNum, DayOfWeekNum, HourNum, MinuteNum)
SELECT
    ts::DATE AS FullDate,
    EXTRACT(YEAR FROM ts)::SMALLINT AS YearNum,
    EXTRACT(MONTH FROM ts)::SMALLINT AS MonthNum,
    EXTRACT(DAY FROM ts)::SMALLINT AS DayNum,
    EXTRACT(ISODOW FROM ts)::SMALLINT AS DayOfWeekNum, 
    EXTRACT(HOUR FROM ts)::SMALLINT AS HourNum,
    EXTRACT(MINUTE FROM ts)::SMALLINT AS MinuteNum
FROM (
    SELECT generate_series(
        '2024-01-01 00:00:00'::TIMESTAMP,
        '2025-12-31 23:59:00'::TIMESTAMP,
        '1 minute'::INTERVAL
    ) AS ts
) AS series
ON CONFLICT (FullDate, HourNum, MinuteNum) DO NOTHING;


--===============================================
-- KROK 3: VYTVOŘENÍ FAKTOVÉ TABULKY - OPRAVA TS103
--===============================================

DROP TABLE IF EXISTS mttgueries.FactCameraDetection CASCADE;
CREATE TABLE mttgueries.FactCameraDetection (
    -- Sekvenční klíč
    CameraDetectionKey BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    
    -- POVINNÝ SLOUPEC PRO TIMESCALEDB
    DetectionTime TIMESTAMPTZ NOT NULL, 

    -- Klíče dimenzí (propojují se s tabulkami Dim*)
    TimeKey INT NOT NULL DEFAULT -1,
    SensorKey INT NOT NULL DEFAULT -1,
    DetectionTypeKey INT NOT NULL DEFAULT -1,
    LPKey INT NOT NULL DEFAULT -1,
    CountryKey INT NOT NULL DEFAULT -1,
    VehicleClassKey INT NOT NULL DEFAULT -1,
    CityKey INT NOT NULL DEFAULT -1,
    Velocity REAL,
    
    -- OPRAVA: Složený Primární Klíč
    -- Musí zahrnovat dělící sloupec (DetectionTime)
    PRIMARY KEY (CameraDetectionKey, DetectionTime), 

    -- Nastavení cizích klíčů
    CONSTRAINT fk_time FOREIGN KEY (TimeKey) REFERENCES mttgueries.DimTime(TimeKey),
    CONSTRAINT fk_sensor FOREIGN KEY (SensorKey) REFERENCES mttgueries.DimSensor(SensorKey),
    CONSTRAINT fk_detectiontype FOREIGN KEY (DetectionTypeKey) REFERENCES mttgueries.DimDetectionType(DetectionTypeKey),
    CONSTRAINT fk_lp FOREIGN KEY (LPKey) REFERENCES mttgueries.DimLP(LPKey),
    CONSTRAINT fk_country FOREIGN KEY (CountryKey) REFERENCES mttgueries.DimCountry(CountryKey),
    CONSTRAINT fk_vehicleclass FOREIGN KEY (VehicleClassKey) REFERENCES mttgueries.DimVehicleClass(VehicleClassKey),
    CONSTRAINT fk_city FOREIGN KEY (CityKey) REFERENCES mttgueries.DimCity(CityKey)
);

--===============================================
-- KROK 4: PŘEVOD NA TIMESCALEDB HYPERTABLE
--===============================================

-- Převod na Hypertable (rozdělení dat po 7 dnech pro rychlé dotazy)
SELECT mttgueries.create_hypertable(
    'mttgueries.FactCameraDetection',
    'detectiontime',
    chunk_time_interval => INTERVAL '7 days'
);

-- Doporučené indexy pro rychlejší JOINy a filtrování (již jsi měl správně)
CREATE INDEX idx_fact_sensorkey ON mttgueries.FactCameraDetection (SensorKey, DetectionTime DESC);
CREATE INDEX idx_fact_citykey ON mttgueries.FactCameraDetection (CityKey, DetectionTime DESC);
CREATE INDEX idx_fact_lpkey ON mttgueries.FactCameraDetection (LPKey, DetectionTime DESC);


--===============================================
-- KROK 5: DOPORUČENÝ INDEX VE STAGING TABULCE
--===============================================

-- 💡 ZRYCHLENÍ: Index na primární klíč (landingid) ve STAGING tabulce 
-- (to je ta, ze které čteš: mttgueries.bilina_decin_kamery)
-- Ten zajistí rychlé filtrování v klauzuli WHERE t.landingid BETWEEN %s AND %s
CREATE INDEX idx_staging_landingid ON mttgueries.bilina_decin_kamery (landingid); 


/*
=================================================
 SKRIPTY ÚSPĚŠNĚ DOKONČENY
=================================================
*/