-- FACT TABULKA
TRUNCATE TABLE FactCameraDetection;

-- DIMENZE
TRUNCATE TABLE DimCity;
TRUNCATE TABLE DimSensor;
TRUNCATE TABLE DimLP;
TRUNCATE TABLE DimDetectionType;
TRUNCATE TABLE DimVehicleClass;
TRUNCATE TABLE DimCountry;
TRUNCATE TABLE DimTime;
